-- Chạy script này trong SQL Editor của Supabase để khởi tạo cấu trúc dữ liệu cho App

-- 1. Tạo bảng lưu trữ Giáo án (Lesson Plans)
create table if not exists lesson_plans (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  topic text,
  subject text,
  grade text,
  content jsonb,
  textbook_url text,
  framework_url text
);

-- 2. Cấu hình Row Level Security (RLS) cho bảng lesson_plans
alter table lesson_plans enable row level security;

-- Cho phép xem giáo án (Public)
create policy "Enable read access for all users"
on lesson_plans for select
using (true);

-- Cho phép thêm giáo án (Public - Demo mode)
create policy "Enable insert access for all users"
on lesson_plans for insert
with check (true);

-- Chỉ cho phép user đã đăng nhập xóa giáo án
create policy "Enable delete for authenticated users only"
on lesson_plans for delete
to authenticated
using (true);

-- 3. Tạo Bucket lưu trữ tài liệu (Storage)
-- Lưu ý: Nếu bucket 'documents' đã tồn tại, lệnh này có thể báo lỗi, hãy bỏ qua.
insert into storage.buckets (id, name, public)
values ('documents', 'documents', true)
on conflict (id) do nothing;

-- 4. Cấu hình Policy cho Storage (Bucket 'documents')
create policy "Public Access Documents"
on storage.objects for select
using ( bucket_id = 'documents' );

create policy "Public Upload Documents"
on storage.objects for insert
with check ( bucket_id = 'documents' );

create policy "Authenticated Delete Documents"
on storage.objects for delete
to authenticated
using ( bucket_id = 'documents' );
