-- Chạy script này trong SQL Editor của Supabase để khởi tạo cấu trúc dữ liệu cho App

-- 1. Tạo bảng lưu trữ Giáo án (Lesson Plans)
create table if not exists lesson_plans (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  topic text,
  subject text,
  grade text,
  content jsonb,
  textbook_url text,
  framework_url text
);

-- 2. Cấu hình Row Level Security (RLS) cho bảng lesson_plans
alter table lesson_plans enable row level security;

-- Cho phép xem giáo án (Public)
create policy "Enable read access for all users"
on lesson_plans for select
using (true);

-- Cho phép thêm giáo án (Public - Demo mode)
create policy "Enable insert access for all users"
on lesson_plans for insert
with check (true);

-- Chỉ cho phép user đã đăng nhập xóa giáo án
create policy "Enable delete for authenticated users only"
on lesson_plans for delete
to authenticated
using (true);

-- 3. Tạo Bucket lưu trữ tài liệu (Storage)
-- Lưu ý: Nếu bucket 'documents' đã tồn tại, lệnh này có thể báo lỗi, hãy bỏ qua.
insert into storage.buckets (id, name, public)
values ('documents', 'documents', true)
on conflict (id) do nothing;

-- 5. Tạo bảng lưu trữ thông tin người dùng (Profiles) để thu thập dữ liệu
create table if not exists profiles (
  id uuid references auth.users on delete cascade primary key,
  email text unique not null,
  full_name text,
  phone text,
  expectations text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table profiles enable row level security;

-- Cho phép người dùng xem thông tin của chính mình
create policy "Users can view own profile"
on profiles for select
using (auth.uid() = id);

-- Cho phép người dùng cập nhật thông tin của chính mình
create policy "Users can update own profile"
on profiles for update
using (auth.uid() = id);

-- Cho phép hệ thống (hoặc người dùng mới) tạo profile
create policy "Enable insert for all users"
on profiles for insert
with check (true);

-- Cho phép Admin xem tất cả profile (nếu cần)
create policy "Admin can view all profiles"
on profiles for select
to authenticated
using (auth.jwt() ->> 'email' = 'anthonydong.genz@gmail.com');
